# -*- coding:utf8 -*-
"""
Created on 15-11-22 下午11:33
@author: FMC

"""
from __future__ import nested_scopes, generators, division, absolute_import, with_statement, print_function

nodegroup_list = [
    {'name': 'web-restapi-01', 'env': 'prod'},
    {'name': 'web-restapi-02', 'env': 'prod'},
    {'name': 'web-misc-01', 'env': 'prod'},
    {'name': 'web-pay-01', 'env': 'prod'},
    {'name': 'web-mux-01', 'env': 'prod'},
    {'name': 'app-api-01', 'env': 'prod'},
    {'name': 'web-proxy-01', 'env': 'prod'},
    {'name': 'web-proxy-02', 'env': 'prod'}
]


node_list = [
    {'hostname': 'xg-web-restapi-1', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-2', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-3', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-6', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-7', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-8', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-9', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-10', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-11', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-12', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-13', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-14', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-16', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-17', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-18', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-19', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-35', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-36', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-56', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-57', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-58', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-59', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-60', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-61', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-62', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-63', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-64', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-65', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-66', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-67', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-68', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-69', 'env': 'prod', 'group': 'web-restapi-01'},
    {'hostname': 'xg-web-restapi-20', 'env': 'prod', 'group': 'web-restapi-02'},
    {'hostname': 'xg-web-restapi-21', 'env': 'prod', 'group': 'web-restapi-02'},
    {'hostname': 'xg-web-restapi-22', 'env': 'prod', 'group': 'web-restapi-02'},
    {'hostname': 'xg-web-restapi-23', 'env': 'prod', 'group': 'web-restapi-02'},
    {'hostname': 'xg-web-restapi-24', 'env': 'prod', 'group': 'web-restapi-02'},
    {'hostname': 'xg-web-restapi-25', 'env': 'prod', 'group': 'web-restapi-02'},
    {'hostname': 'xg-web-restapi-26', 'env': 'prod', 'group': 'web-restapi-02'},
    {'hostname': 'xg-web-restapi-27', 'env': 'prod', 'group': 'web-restapi-02'},
    {'hostname': 'xg-web-restapi-28', 'env': 'prod', 'group': 'web-restapi-02'},
    {'hostname': 'xg-web-restapi-29', 'env': 'prod', 'group': 'web-restapi-02'},
    {'hostname': 'xg-web-restapi-30', 'env': 'prod', 'group': 'web-restapi-02'},
    {'hostname': 'xg-web-restapi-40', 'env': 'prod', 'group': 'web-restapi-02'},
    {'hostname': 'xg-web-restapi-41', 'env': 'prod', 'group': 'web-restapi-02'},
    {'hostname': 'xg-web-restapi-42', 'env': 'prod', 'group': 'web-restapi-02'},
    {'hostname': 'xg-web-restapi-43', 'env': 'prod', 'group': 'web-restapi-02'},
    {'hostname': 'xg-web-restapi-44', 'env': 'prod', 'group': 'web-restapi-02'},
    {'hostname': 'xg-web-restapi-45', 'env': 'prod', 'group': 'web-restapi-02'},
    {'hostname': 'xg-web-restapi-46', 'env': 'prod', 'group': 'web-restapi-02'},
    {'hostname': 'xg-web-restapi-47', 'env': 'prod', 'group': 'web-restapi-02'},
    {'hostname': 'xg-web-restapi-48', 'env': 'prod', 'group': 'web-restapi-02'},
    {'hostname': 'xg-web-restapi-49', 'env': 'prod', 'group': 'web-restapi-02'},
    {'hostname': 'xg-web-restapi-50', 'env': 'prod', 'group': 'web-restapi-02'},
    {'hostname': 'xg-web-restapi-51', 'env': 'prod', 'group': 'web-restapi-02'},
    {'hostname': 'xg-web-restapi-52', 'env': 'prod', 'group': 'web-restapi-02'},
    {'hostname': 'xg-web-restapi-53', 'env': 'prod', 'group': 'web-restapi-02'},
    {'hostname': 'xg-web-restapi-54', 'env': 'prod', 'group': 'web-restapi-02'},
    {'hostname': 'xg-web-restapi-55', 'env': 'prod', 'group': 'web-restapi-02'},
    {'hostname': 'xg-web-misc-1', 'env': 'prod', 'group': 'web-misc-01'},
    {'hostname': 'xg-web-misc-2', 'env': 'prod', 'group': 'web-misc-01'},
    {'hostname': 'xg-web-misc-3', 'env': 'prod', 'group': 'web-misc-01'},
    {'hostname': 'xg-web-misc-4', 'env': 'prod', 'group': 'web-misc-01'},
    {'hostname': 'xg-web-misc-5', 'env': 'prod', 'group': 'web-misc-01'},
    {'hostname': 'xg-web-misc-6', 'env': 'prod', 'group': 'web-misc-01'},
    {'hostname': 'xg-web-misc-7', 'env': 'prod', 'group': 'web-misc-01'},
    {'hostname': 'xg-web-misc-8', 'env': 'prod', 'group': 'web-misc-01'},
    {'hostname': 'xg-web-misc-9', 'env': 'prod', 'group': 'web-misc-01'},
    {'hostname': 'xg-web-misc-10', 'env': 'prod', 'group': 'web-misc-01'},
    {'hostname': 'xg-web-misc-11', 'env': 'prod', 'group': 'web-misc-01'},
    {'hostname': 'xg-web-misc-12', 'env': 'prod', 'group': 'web-misc-01'},
    {'hostname': 'xg-web-misc-13', 'env': 'prod', 'group': 'web-misc-01'},
    {'hostname': 'xg-web-misc-14', 'env': 'prod', 'group': 'web-misc-01'},
    {'hostname': 'xg-web-misc-15', 'env': 'prod', 'group': 'web-misc-01'},
    {'hostname': 'xg-web-misc-16', 'env': 'prod', 'group': 'web-misc-01'},
    {'hostname': 'xg-web-misc-17', 'env': 'prod', 'group': 'web-misc-01'},
    {'hostname': 'xg-web-misc-18', 'env': 'prod', 'group': 'web-misc-01'},
    {'hostname': 'xg-web-misc-19', 'env': 'prod', 'group': 'web-misc-01'},
    {'hostname': 'xg-web-misc-20', 'env': 'prod', 'group': 'web-misc-01'},
    {'hostname': 'xg-web-misc-21', 'env': 'prod', 'group': 'web-misc-01'},
    {'hostname': 'xg-web-misc-22', 'env': 'prod', 'group': 'web-misc-01'},
    {'hostname': 'xg-web-misc-23', 'env': 'prod', 'group': 'web-misc-01'},
    {'hostname': 'xg-web-misc-24', 'env': 'prod', 'group': 'web-misc-01'},
    {'hostname': 'xg-web-misc-25', 'env': 'prod', 'group': 'web-misc-01'},
    {'hostname': 'xg-web-misc-26', 'env': 'prod', 'group': 'web-misc-01'},
    {'hostname': 'xg-web-misc-27', 'env': 'prod', 'group': 'web-misc-01'},
    {'hostname': 'xg-web-pay-1', 'env': 'prod', 'group': 'web-pay-01'},
    {'hostname': 'xg-web-pay-2', 'env': 'prod', 'group': 'web-pay-01'},
    {'hostname': 'xg-web-pay-3', 'env': 'prod', 'group': 'web-pay-01'},
    {'hostname': 'xg-web-pay-4', 'env': 'prod', 'group': 'web-pay-01'},
    {'hostname': 'xg-web-pay-5', 'env': 'prod', 'group': 'web-pay-01'},
    {'hostname': 'xg-web-pay-6', 'env': 'prod', 'group': 'web-pay-01'},
    {'hostname': 'xg-web-pay-7', 'env': 'prod', 'group': 'web-pay-01'},
    {'hostname': 'xg-web-pay-8', 'env': 'prod', 'group': 'web-pay-01'},
    {'hostname': 'xg-web-pay-9', 'env': 'prod', 'group': 'web-pay-01'},
    {'hostname': 'xg-web-mux-1', 'env': 'prod', 'group': 'web-mux-01'},
    {'hostname': 'xg-web-mux-2', 'env': 'prod', 'group': 'web-mux-01'},
    {'hostname': 'xg-web-mux-3', 'env': 'prod', 'group': 'web-mux-01'},
    {'hostname': 'xg-web-mux-4', 'env': 'prod', 'group': 'web-mux-01'},
    {'hostname': 'xg-app-api-1', 'env': 'prod', 'group': 'app-api-01'},
    {'hostname': 'xg-app-api-2', 'env': 'prod', 'group': 'app-api-01'},
    {'hostname': 'xg-app-api-3', 'env': 'prod', 'group': 'app-api-01'},
    {'hostname': 'xg-app-api-4', 'env': 'prod', 'group': 'app-api-01'},
    {'hostname': 'xg-app-api-5', 'env': 'prod', 'group': 'app-api-01'},
    {'hostname': 'xg-app-api-6', 'env': 'prod', 'group': 'app-api-01'},
    {'hostname': 'xg-app-api-7', 'env': 'prod', 'group': 'app-api-01'},
    {'hostname': 'xg-app-api-8', 'env': 'prod', 'group': 'app-api-01'},
    {'hostname': 'xg-app-api-9', 'env': 'prod', 'group': 'app-api-01'},
    {'hostname': 'xg-app-api-10', 'env': 'prod', 'group': 'app-api-01'},
    {'hostname': 'xg-app-api-11', 'env': 'prod', 'group': 'app-api-01'},
    {'hostname': 'xg-app-api-12', 'env': 'prod', 'group': 'app-api-01'},
    {'hostname': 'xg-web-proxy-1', 'env': 'prod', 'group': 'web-proxy-01'},
    {'hostname': 'xg-web-proxy-2', 'env': 'prod', 'group': 'web-proxy-01'},
    {'hostname': 'xg-web-proxy-3', 'env': 'prod', 'group': 'web-proxy-01'},
    {'hostname': 'xg-web-proxy-4', 'env': 'prod', 'group': 'web-proxy-02'},
    {'hostname': 'xg-web-proxy-5', 'env': 'prod', 'group': 'web-proxy-02'},
    {'hostname': 'xg-web-proxy-6', 'env': 'prod', 'group': 'web-proxy-02'},
]
